import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './font.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: '부산 203 가이드',
  description: "Generated by create next app",
  verification: {
    google: 'BtCWRwrlx5Q853WJFhPYc6UjB2zIz6PJHtQr-lEP3Mo',
    naver: '7501b018b4c16791bcc5a2900947326985a96386',
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
